### ISSUE TITLE
[Project 0] Adding new vmdk crashes the VM? (MacOS)

### ISSUE THREAD

**Issue by kwanyoungpark** [Jim741305/osfall2020#6]
Following the tutorial (from https://blog.lobraun.de/2015/06/06/mount-sd-cards-within-virtualbox-on-mac-os-x/), I was able to make vmdk file and attached it.
 However, now VM is stuck in "blinking cursor" (similar to when quiet splash problem occurred). I tried multiple times with different configurations, but the result was the same. Would it be the problem of VM itself? or I missed something?

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox instead.

**Comment by kwanyoungpark** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox

**Comment by GGOSinon** [comment]
Solved: Followed https://dzone.com/articles/how-to-mount-usb-drives-on-virtualbox
